ControlFocus("Abrir","","Edit1")
Sleep(2000)
ControlSetText("Abrir","","Edit1","D:\Pruebas_Selenium\E2E_Test\E2E_Pruebas\resources\ServiceRequest\diagram.bpmn")
Sleep(2000)
ControlClick("Abrir","","Button1")
